const CollectionTypes = {
    UPDATE_SHOP_DATA : 'UPDATE_SHOP_DATA',
    FETHCING_SHOP_DATA_START:'FETHCING_SHOP_DATA_START',
    FETHCING_SHOP_DATA_SUCCESS:'FETHCING_SHOP_DATA_SUCCESS',
    FETHCING_SHOP_DATA_FAILED:'FETHCING_SHOP_DATA_FAILED',

}

export default CollectionTypes;