export const userActionTypes = {
    SET_CURRENT_USER:'SET_CURRENT_USER',

    LOGIN_WITH_GOOGLE_START:'LOGIN_WITH_GOOGLE_START',
    LOGIN_WITH_EMAIL_PASSWORD_START:'LOGIN_WITH_EMAIL_PASSWORD_START',
   
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    
    CHECK_USER_SESSION:'CHECK_USER_SESSION',

    LOGOUT_START:'LOGOUT_START',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED',

    SIGNUP_START:'SIGNUP_START',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILED:'SIGNUP_FAILED'
}